---
- hosts: default
  become: true
  tasks:
  - name: Install Apache packages 
    apt:
      name: apache2
      state: present
  - name: Create website root
    file:
      path: /var/www/html/bookapp
      state: directory
      owner: www-data
      mode: '0755'
  - name: Copy website
    copy:
      dest: /var/www/html/bookapp
      src: /home/cloud_user/ansible/files/bookapp/
      owner: www-data
  - name: Add website configuration
    file:
      path: /etc/apache2/sites-available/
      src: /home/cloud_user/ansible/files/bookapp.conf
      owner: root
  - name: Disable default website
    command: a2dissite 000-default.conf
  - name: Enable Bookapp website
    command: a2ensite bookapp.conf
  - name: Ensure Apache is running
    service:
      name: apache2
      state: started
